// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using WanderTale;

#nullable disable

namespace WanderTale.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506153000_AddPhotoDateAndLocation")]
    partial class AddPhotoDateAndLocation
    {
    }
}
